/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.soltelec.util;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.soltelec.util.RecogerDatosOpacimetro;

/**
 *
 * @author Gerencia Desarrollo de Soluciones Tecnologicas
 */
public class PanelTiempoRepuestaOpacimetro extends javax.swing.JPanel {

   RecogerDatosOpacimetro monitoreo;
   private XYDataset dataset1 = new XYSeriesCollection();
    private final XYSeries Serie1 = new XYSeries("Señal");
    private int tiempo = 0;

    /**
     * Creates new form PanelConfiguracion
     */
    public PanelTiempoRepuestaOpacimetro(RecogerDatosOpacimetro monitoreo) {
        try {
            this.monitoreo=monitoreo;
        initComponents();
        this.setSize(this.getToolkit().getScreenSize());
            initComponents();
            
        } catch (Exception ex) {  }
      ConfigurarDatos();
    }
    void ConfigurarDatos() {
        dataset1 = new XYSeriesCollection(Serie1);
        jLineChart1.setDataset(dataset1);
        Serie1.setMaximumItemCount(1344);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblUsuario4 = new javax.swing.JLabel();
        jLineChart1 = new org.jfree.beans.JLineChart();
        jSeparator3 = new javax.swing.JSeparator();
        BotonRecal = new javax.swing.JButton();
        BotonRecal1 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jToggleButton1.setText("escribir Configuracion");
        jToggleButton1.setToolTipText("");
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\HTML5Application\\public_html\\img\\user.png")); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        lblUsuario4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario4.setText("Verificacion Tiempos de Respuesta");
        lblUsuario4.setToolTipText("");

        jLineChart1.setSource("SOLTELEC S.A.S");
        jLineChart1.setSubtitle("Opacidad vs Tiempo");
        jLineChart1.setTitle("% opacidad");
        jLineChart1.setXAxisLabel("Tiempo (s)");
        jLineChart1.setYAxisLabel("Opacidad (oP)");

        javax.swing.GroupLayout jLineChart1Layout = new javax.swing.GroupLayout(jLineChart1);
        jLineChart1.setLayout(jLineChart1Layout);
        jLineChart1Layout.setHorizontalGroup(
            jLineChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        jLineChart1Layout.setVerticalGroup(
            jLineChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        BotonRecal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonRecal.setText("Disparar Trigger");
        BotonRecal.setToolTipText("");
        BotonRecal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecalActionPerformed(evt);
            }
        });

        BotonRecal1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotonRecal1.setText("Disparar Pre Trigger");
        BotonRecal1.setToolTipText("");
        BotonRecal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 217, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRecal)
                .addGap(257, 257, 257))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLineChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(BotonRecal1)
                    .addContainerGap(437, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario4)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(BotonRecal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jLineChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(548, Short.MAX_VALUE)
                    .addComponent(BotonRecal1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );

        lblUsuario4.getAccessibleContext().setAccessibleName("Verificacion de Tiempos de Respuestas");
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       FileOutputStream os=null;
        try {
            
            JOptionPane.showMessageDialog(null, "Configuracion Exitosa ..!");//debe bloquear el equipo
        } catch (Exception ex) {
            Logger.getLogger(PanelTiempoRepuestaOpacimetro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                os.close();
            } catch (IOException ex) {
                Logger.getLogger(PanelTiempoRepuestaOpacimetro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void BotonRecalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecalActionPerformed
        
    }//GEN-LAST:event_BotonRecalActionPerformed

    private void BotonRecal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRecal1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRecal;
    private javax.swing.JButton BotonRecal1;
    private org.jfree.beans.JLineChart jLineChart1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUsuario4;
    // End of variables declaration//GEN-END:variables
}
