/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.soltelec.procesosbanco.verificacion;

import eu.hansolo.steelseries.tools.LcdColor;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JProgressBar;
import org.soltelec.util.MedicionGases;

/**
 *Clase que muestra los valores de las pipetas y los valores que el
 * banco esta midiendo actualmente si los valores estan por fuera del
 * rango de verificacion, entonces saldra en color rojo, si los valores estan
 * correctos entonces el color será azul
 * 
 * @author User
 */
public class PanelVerificacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelVerificacion
     */
    
    private TipoMuestra tipoMuestra;
    
    private MedicionGases medicion;
    
    private int pef;
    
    private double valorPef;
    
    public void setTipoMuestra(TipoMuestra tipo){
        
        this.tipoMuestra = tipo;
        this.displayMuestraHC.setLcdValue( tipoMuestra.getValorHC() );
        this.displayMuestraCO.setLcdValue( tipoMuestra.getValorCO() );
        this.displayMuestraCO2.setLcdValue( tipoMuestra.getValorCO2() );
        this.repaint();
        SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss ");
        labelText.setText(sd.format(new Date()));
    }
    
    public void setMedicionGases(MedicionGases med){
        this.medicion = med;
        repintarDisplays();
    }
    
    public PanelVerificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        displayMedidaCO = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displayMedidaCO2 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displayMedidaO2 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        displayMedidaHC = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        displayMuestraCO = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displayMuestraCO2 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displayMuestraO2 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        displayMuestraHC = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jProgressBar1 = new javax.swing.JProgressBar();
        labelText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores Medidos"));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("HC");

        displayMedidaCO.setDigitalFont(true);
        displayMedidaCO.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLUEBLUE_LCD);
        displayMedidaCO.setLcdDecimals(2);
        displayMedidaCO.setLcdUnitString("%");

        javax.swing.GroupLayout displayMedidaCOLayout = new javax.swing.GroupLayout(displayMedidaCO);
        displayMedidaCO.setLayout(displayMedidaCOLayout);
        displayMedidaCOLayout.setHorizontalGroup(
            displayMedidaCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayMedidaCOLayout.setVerticalGroup(
            displayMedidaCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        displayMedidaCO2.setDigitalFont(true);
        displayMedidaCO2.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLUEBLUE_LCD);
        displayMedidaCO2.setLcdUnitString("%");

        javax.swing.GroupLayout displayMedidaCO2Layout = new javax.swing.GroupLayout(displayMedidaCO2);
        displayMedidaCO2.setLayout(displayMedidaCO2Layout);
        displayMedidaCO2Layout.setHorizontalGroup(
            displayMedidaCO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        displayMedidaCO2Layout.setVerticalGroup(
            displayMedidaCO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        displayMedidaO2.setDigitalFont(true);
        displayMedidaO2.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLUEBLUE_LCD);
        displayMedidaO2.setLcdDecimals(2);
        displayMedidaO2.setLcdUnitString("%");

        javax.swing.GroupLayout displayMedidaO2Layout = new javax.swing.GroupLayout(displayMedidaO2);
        displayMedidaO2.setLayout(displayMedidaO2Layout);
        displayMedidaO2Layout.setHorizontalGroup(
            displayMedidaO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        displayMedidaO2Layout.setVerticalGroup(
            displayMedidaO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("O2");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("CO");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("CO2");

        displayMedidaHC.setDigitalFont(true);
        displayMedidaHC.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLUEBLUE_LCD);
        displayMedidaHC.setLcdDecimals(0);
        displayMedidaHC.setLcdUnitString("ppm");

        javax.swing.GroupLayout displayMedidaHCLayout = new javax.swing.GroupLayout(displayMedidaHC);
        displayMedidaHC.setLayout(displayMedidaHCLayout);
        displayMedidaHCLayout.setHorizontalGroup(
            displayMedidaHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        displayMedidaHCLayout.setVerticalGroup(
            displayMedidaHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayMedidaO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayMedidaCO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(displayMedidaHC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayMedidaCO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayMedidaHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayMedidaCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayMedidaCO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayMedidaO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor Pipetas"));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("HC");

        displayMuestraCO.setDigitalFont(true);
        displayMuestraCO.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLACK_LCD);
        displayMuestraCO.setLcdDecimals(0);
        displayMuestraCO.setLcdUnitString("%");

        javax.swing.GroupLayout displayMuestraCOLayout = new javax.swing.GroupLayout(displayMuestraCO);
        displayMuestraCO.setLayout(displayMuestraCOLayout);
        displayMuestraCOLayout.setHorizontalGroup(
            displayMuestraCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayMuestraCOLayout.setVerticalGroup(
            displayMuestraCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        displayMuestraCO2.setDigitalFont(true);
        displayMuestraCO2.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLACK_LCD);
        displayMuestraCO2.setLcdDecimals(0);
        displayMuestraCO2.setLcdUnitString("%");

        javax.swing.GroupLayout displayMuestraCO2Layout = new javax.swing.GroupLayout(displayMuestraCO2);
        displayMuestraCO2.setLayout(displayMuestraCO2Layout);
        displayMuestraCO2Layout.setHorizontalGroup(
            displayMuestraCO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        displayMuestraCO2Layout.setVerticalGroup(
            displayMuestraCO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        displayMuestraO2.setDigitalFont(true);
        displayMuestraO2.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLACK_LCD);
        displayMuestraO2.setLcdDecimals(0);
        displayMuestraO2.setLcdUnitString("%");

        javax.swing.GroupLayout displayMuestraO2Layout = new javax.swing.GroupLayout(displayMuestraO2);
        displayMuestraO2.setLayout(displayMuestraO2Layout);
        displayMuestraO2Layout.setHorizontalGroup(
            displayMuestraO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayMuestraO2Layout.setVerticalGroup(
            displayMuestraO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("O2");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("CO");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("CO2");

        displayMuestraHC.setDigitalFont(true);
        displayMuestraHC.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLACK_LCD);
        displayMuestraHC.setLcdDecimals(0);
        displayMuestraHC.setLcdUnitString("ppm");

        javax.swing.GroupLayout displayMuestraHCLayout = new javax.swing.GroupLayout(displayMuestraHC);
        displayMuestraHC.setLayout(displayMuestraHCLayout);
        displayMuestraHCLayout.setHorizontalGroup(
            displayMuestraHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayMuestraHCLayout.setVerticalGroup(
            displayMuestraHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(displayMuestraCO2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayMuestraCO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayMuestraHC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayMuestraO2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayMuestraHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayMuestraCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayMuestraCO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayMuestraO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        jProgressBar1.setMaximum(10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMedidaCO;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMedidaCO2;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMedidaHC;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMedidaO2;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMuestraCO;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMuestraCO2;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMuestraHC;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMuestraO2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel labelText;
    // End of variables declaration//GEN-END:variables

    /**
     * Repinta los rangos dependiendo si los valroes estan dentro del rango
     * de tolerancia para la norma
     */
    private void repintarDisplays() {
        
        displayMedidaHC.setLcdValue(medicion.getValorHC()/valorPef);
        displayMedidaCO.setLcdValue(medicion.getValorCO()*0.01);
        displayMedidaCO2.setLcdValue(medicion.getValorCO2()*0.1);
        displayMedidaO2.setLcdValue(medicion.getValorO2()*0.01);
        
        if(UtilVerificacion.estaEnRangoHC(tipoMuestra,(int)(medicion.getValorHC()/valorPef)) ){
            
            displayMedidaHC.setLcdColor(LcdColor.BLUEBLUE_LCD);
            
            
        } 
        else {
            
            displayMedidaHC.setLcdColor(LcdColor.RED_LCD);
            
        }
        
        if(UtilVerificacion.estaEnRangoCO(tipoMuestra,medicion.getValorCO()*0.01)){
            
            displayMedidaCO.setLcdColor(LcdColor.BLUEBLUE_LCD);
            
        } else {
            
            displayMedidaCO.setLcdColor(LcdColor.RED_LCD);
        }
        
        if(UtilVerificacion.estaEnRangoCO2(tipoMuestra,medicion.getValorCO2()*0.1)){
            
            displayMedidaCO2.setLcdColor(LcdColor.BLUEBLUE_LCD);
        }
        else {
            displayMedidaCO2.setLcdColor(LcdColor.RED_LCD);
            
        }
        this.repaint();
        //this.revalidate();
        
        
    }

    public JProgressBar getjProgressBar1() {
        return jProgressBar1;
    }

    public int getPef() {
        return pef;
    }

    public void setPef(int pef) {
        this.pef = pef;
        
        setValorPef(pef*0.001);
        
        
    }

    public double getValorPef() {
        return valorPef;
    }

    public void setValorPef(double valorPef) {
        this.valorPef = valorPef;
    }



    
}
