/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.soltelec.procesosbanco;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.soltelec.util.Conex;

/**
 *
 * @author Gerencia Desarrollo de Soluciones Tecnologicas
 */
public class PanelPipetas extends javax.swing.JPanel {

    Properties props = new Properties();

    /**
     * Creates new form PanelConfiguracion
     */
    public PanelPipetas() {
        try {
            initComponents();
            props.load(new FileInputStream("equipos.properties"));
            PBHC1.setText(String.valueOf(props.getProperty("PBHC").trim()));
            PBCO.setText(String.valueOf(props.getProperty("PBCO").trim()));
            PBCO2.setText(String.valueOf(props.getProperty("PBCO2").trim()));
            PAHC.setText(String.valueOf(props.getProperty("PAHC").trim()));
            PACO.setText(String.valueOf(props.getProperty("PACO").trim()));
            PACO2.setText(String.valueOf(props.getProperty("PACO2").trim()));

            PBHC2T.setText(String.valueOf(props.getProperty("PBHC2T").trim()));
            PBCO2T.setText(String.valueOf(props.getProperty("PBCO2T").trim()));
            PBCO22T.setText(String.valueOf(props.getProperty("PBCO22T").trim()));
            PAHC2T.setText(String.valueOf(props.getProperty("PAHC2T").trim()));
            PACO2T.setText(String.valueOf(props.getProperty("PACO2T").trim()));
            PACO22T.setText(String.valueOf(props.getProperty("PACO22T").trim()));

            LABPALTA.setText(String.valueOf(props.getProperty("LABPIPETAALTA").trim()));
            CILPALTA.setText(String.valueOf(props.getProperty("CILPIPETAALTA").trim()));
            CERPALTA.setText(String.valueOf(props.getProperty("CERPIPETAALTA").trim()));
            LABPBAJA.setText(String.valueOf(props.getProperty("LABPIPETABAJA").trim()));
            CILPBAJA.setText(String.valueOf(props.getProperty("CILPIPETABAJA").trim()));
            CERPBAJA.setText(String.valueOf(props.getProperty("CERPIPETABAJA").trim()));

        } catch (Exception ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        PACO2 = new javax.swing.JTextField();
        PBCO = new javax.swing.JTextField();
        lblUsuario1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        lblUsuario3 = new javax.swing.JLabel();
        PAHC = new javax.swing.JTextField();
        lblPAHC = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblUsuario4 = new javax.swing.JLabel();
        lblUsuario5 = new javax.swing.JLabel();
        PACO = new javax.swing.JTextField();
        PBHC1 = new javax.swing.JTextField();
        PBCO2 = new javax.swing.JTextField();
        lblUsuario6 = new javax.swing.JLabel();
        lblUsuario7 = new javax.swing.JLabel();
        PBHC2T = new javax.swing.JTextField();
        lblUsuario8 = new javax.swing.JLabel();
        PBCO2T = new javax.swing.JTextField();
        lblUsuario9 = new javax.swing.JLabel();
        PBCO22T = new javax.swing.JTextField();
        lblPAHC1 = new javax.swing.JLabel();
        PAHC2T = new javax.swing.JTextField();
        lblUsuario10 = new javax.swing.JLabel();
        PACO2T = new javax.swing.JTextField();
        lblUsuario11 = new javax.swing.JLabel();
        PACO22T = new javax.swing.JTextField();
        lblUsuario12 = new javax.swing.JLabel();
        lblUsuario13 = new javax.swing.JLabel();
        lblUsuario14 = new javax.swing.JLabel();
        lblUsuario15 = new javax.swing.JLabel();
        lblUsuario16 = new javax.swing.JLabel();
        lblUsuario17 = new javax.swing.JLabel();
        LABPALTA = new javax.swing.JTextField();
        CERPALTA = new javax.swing.JTextField();
        CILPALTA = new javax.swing.JTextField();
        LABPBAJA = new javax.swing.JTextField();
        CILPBAJA = new javax.swing.JTextField();
        CERPBAJA = new javax.swing.JTextField();

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setText("PBHC");

        PACO2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PBCO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PBCO.setToolTipText("");

        lblUsuario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario1.setText("PBCO");

        lblUsuario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario2.setText("PBCO2");

        lblUsuario3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario3.setText("PACO");

        PAHC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPAHC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPAHC.setText("PAHC");

        jToolBar1.setRollover(true);

        jToggleButton1.setText("escribir Configuracion");
        jToggleButton1.setToolTipText("");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        lblUsuario4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario4.setText("CONFIGURACION APLICADA A PIPETAS 4 TIEMPOS");

        lblUsuario5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario5.setText("PACO2");

        PACO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PBHC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PBCO2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUsuario6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario6.setText("CONFIGURACION APLICADA A PIPETAS 2 TIEMPOS");

        lblUsuario7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario7.setText("PBHC");

        PBHC2T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUsuario8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario8.setText("PBCO");

        PBCO2T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PBCO2T.setToolTipText("");

        lblUsuario9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario9.setText("PBCO2");

        PBCO22T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPAHC1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPAHC1.setText("PAHC");

        PAHC2T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUsuario10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario10.setText("PACO");

        PACO2T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUsuario11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario11.setText("PACO2");

        PACO22T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUsuario12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario12.setText("CILINDRO PIPETA ALTA");

        lblUsuario13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario13.setText("LABORATORIO PIPETA ALTA");

        lblUsuario14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario14.setText("CERTIFICADO PIPETA ALTA");

        lblUsuario15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario15.setText("CILINDRO PIPETA BAJA");

        lblUsuario16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario16.setText("CERTIFICADO PIPETA BAJA");

        lblUsuario17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario17.setText("LABORATORIO PIPETA BAJA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUsuario1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PBCO2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PBHC1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PBCO, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPAHC, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblUsuario11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PACO2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PACO, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PAHC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUsuario14, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(lblUsuario7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblUsuario8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                                    .addComponent(lblUsuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(44, 44, 44)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PBCO2T, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PBHC2T, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PBCO22T, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(LABPALTA)
                                                    .addComponent(CILPALTA)
                                                    .addComponent(CERPALTA, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblUsuario17, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblUsuario16, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblUsuario15, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(LABPBAJA)
                                                    .addComponent(CILPBAJA)
                                                    .addComponent(CERPBAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 40, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblUsuario10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPAHC1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(PAHC2T, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(PACO2T, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(PACO22T, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(125, 125, 125))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUsuario12, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUsuario13, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario4)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(PBHC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario1)
                            .addComponent(PBCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario2)
                            .addComponent(PBCO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PAHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PACO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPAHC)
                                .addGap(18, 18, 18)
                                .addComponent(lblUsuario3)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PACO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario7)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario8)
                        .addGap(14, 14, 14)
                        .addComponent(lblUsuario9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPAHC1)
                            .addComponent(PAHC2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario10)
                            .addComponent(PACO2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario5)
                            .addComponent(PACO22T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PBHC2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PBCO2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addComponent(PBCO22T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario13)
                            .addComponent(lblUsuario17)
                            .addComponent(LABPALTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario12)
                            .addComponent(lblUsuario15)
                            .addComponent(CILPALTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario14)
                            .addComponent(lblUsuario16)
                            .addComponent(CERPALTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LABPBAJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CILPBAJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CERPBAJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        FileOutputStream os = null;
        try {
            os = new FileOutputStream("equipos.properties");
            props.setProperty("PBHC", PBHC1.getText());
            props.setProperty("PBCO", PBCO.getText());
            props.setProperty("PBCO2", PBCO2.getText());
            props.setProperty("PAHC", PAHC.getText());
            props.setProperty("PACO", PACO.getText());
            props.setProperty("PACO2", PACO2.getText());
            props.setProperty("PBHC2T", PBHC2T.getText());
            props.setProperty("PBCO2T", PBCO2T.getText());
            props.setProperty("PBCO22T", PBCO22T.getText());
            props.setProperty("PAHC2T", PAHC2T.getText());
            props.setProperty("PACO2T", PACO2T.getText());
            props.setProperty("PACO22T", PACO22T.getText());

            props.setProperty("LABPIPETAALTA", LABPALTA.getText());
            props.setProperty("CILPIPETAALTA", CILPALTA.getText());
            props.setProperty("CERPIPETAALTA", CERPALTA.getText());
            props.setProperty("LABPIPETABAJA", LABPALTA.getText());
            props.setProperty("CILPIPETABAJA", CILPBAJA.getText());
            props.setProperty("CERPIPETABAJA", CERPBAJA.getText());
            props.store(os, "");

            JOptionPane.showMessageDialog(null, "Configuracion Exitosa ..!");//debe bloquear el equipo
        } catch (Exception ex) {
            Logger.getLogger(PanelPipetas.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                os.close();
            } catch (IOException ex) {
                Logger.getLogger(PanelPipetas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public void insertarRegistro(Date fecha, String certificadoBaja, String laboratorioBaja) throws ClassNotFoundException {
        String sql = "INSERT INTO Gases (fecha, certificado, laboratorio) VALUES (?, ?, ?)";

        try (Connection conn = Conex.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // Convierte la fecha de Java a java.sql.Date
            java.sql.Date fechaSQL = new java.sql.Date(fecha.getTime());

            pstmt.setDate(1, fechaSQL);
            pstmt.setString(2, certificadoBaja);
            pstmt.setString(3, laboratorioBaja);

            pstmt.executeUpdate();
            System.out.println("Registro insertado correctamente en la tabla Gases.");
        } catch (SQLException e) {
            System.err.println("Error al insertar el registro: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CERPALTA;
    private javax.swing.JTextField CERPBAJA;
    private javax.swing.JTextField CILPALTA;
    private javax.swing.JTextField CILPBAJA;
    private javax.swing.JTextField LABPALTA;
    private javax.swing.JTextField LABPBAJA;
    private javax.swing.JTextField PACO;
    private javax.swing.JTextField PACO2;
    private javax.swing.JTextField PACO22T;
    private javax.swing.JTextField PACO2T;
    private javax.swing.JTextField PAHC;
    private javax.swing.JTextField PAHC2T;
    private javax.swing.JTextField PBCO;
    private javax.swing.JTextField PBCO2;
    private javax.swing.JTextField PBCO22T;
    private javax.swing.JTextField PBCO2T;
    private javax.swing.JTextField PBHC1;
    private javax.swing.JTextField PBHC2T;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblPAHC;
    private javax.swing.JLabel lblPAHC1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario10;
    private javax.swing.JLabel lblUsuario11;
    private javax.swing.JLabel lblUsuario12;
    private javax.swing.JLabel lblUsuario13;
    private javax.swing.JLabel lblUsuario14;
    private javax.swing.JLabel lblUsuario15;
    private javax.swing.JLabel lblUsuario16;
    private javax.swing.JLabel lblUsuario17;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JLabel lblUsuario6;
    private javax.swing.JLabel lblUsuario7;
    private javax.swing.JLabel lblUsuario8;
    private javax.swing.JLabel lblUsuario9;
    // End of variables declaration//GEN-END:variables
}

