/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.soltelec.pruebasgases;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.soltelec.util.UtilPropiedades;

/**
 *
 * @author Gerencia Desarrollo de Soluciones Tecnologicas
 */
public class PanelVerificacionMoto extends javax.swing.JPanel implements java.awt.event.ActionListener {

    private final Set<Integer> conjuntoDefectos = new LinkedHashSet<>();
    private StringBuilder mensaje;
    private boolean defectoEncontrado;
    private StringBuilder detalleRechazo;
    private Map<Integer, String> mapStrRechazos = new HashMap<Integer, String>();
    String str;

    /**
     * Creates new form PanelVerificacionV2
     */
    public PanelVerificacionMoto(boolean ActivarTapaLlenado, boolean ActivarSalidasAdicional) 
    {
        initComponents();
        Dimension d = new java.awt.Dimension(583, 90);
        this.setSize(583, 127);
        setSize(d);
        tapaCombustible.setVisible(ActivarTapaLlenado);
        SalidasDiseno.setVisible(ActivarSalidasAdicional);
    }

    public boolean isDefectoEncontrado() {
        return defectoEncontrado;
    }

    public StringBuilder getMensaje() {
        return mensaje;
    }

    public Set<Integer> getConjuntoDefectos() {
        return conjuntoDefectos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fugasTubo = new javax.swing.JCheckBox();
        fugasTubo.addActionListener(this);
        salidasAdicionales = new javax.swing.JCheckBox();
        salidasAdicionales.addActionListener(this);
        AusenciaTaponesAceite = new javax.swing.JCheckBox();
        AusenciaTaponesAceite.addActionListener(this);
        jLabel1 = new javax.swing.JLabel();
        tapaCombustible = new javax.swing.JCheckBox();
        tapaCombustible.addActionListener(this);
        SalidasDiseno = new javax.swing.JCheckBox();
        SalidasDiseno.addActionListener(this);

        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 300));

        fugasTubo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fugasTubo.setText("<html>Existencia de fugas en el tubo, uniones del múltiple y silenciador del sistema de escape del vehículo</html>");
        fugasTubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fugasTuboActionPerformed(evt);
            }
        });

        salidasAdicionales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salidasAdicionales.setText("<html>Salidas adicionales en el sistema de escape diferentes a las de diseño original del vehículo</html>");

        AusenciaTaponesAceite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AusenciaTaponesAceite.setText("<html>Ausencia de tapones de aceite o fugas en el mismo </html>");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VERIFICACION CONDICIONES ANORMALES");

        tapaCombustible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tapaCombustible.setText("Presencia tapa llenado combustible");
        tapaCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tapaCombustibleActionPerformed(evt);
            }
        });

        SalidasDiseno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SalidasDiseno.setText("Salidas adicionales a las del diseño");
        SalidasDiseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidasDisenoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 118, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 131, Short.MAX_VALUE))
            .addComponent(salidasAdicionales)
            .addComponent(AusenciaTaponesAceite)
            .addComponent(fugasTubo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tapaCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(SalidasDiseno, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fugasTubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salidasAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AusenciaTaponesAceite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tapaCombustible)
                .addGap(18, 18, 18)
                .addComponent(SalidasDiseno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tapaCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tapaCombustibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tapaCombustibleActionPerformed

    private void SalidasDisenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidasDisenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalidasDisenoActionPerformed

    private void fugasTuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fugasTuboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fugasTuboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AusenciaTaponesAceite;
    private javax.swing.JCheckBox SalidasDiseno;
    private javax.swing.JCheckBox fugasTubo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox salidasAdicionales;
    private javax.swing.JCheckBox tapaCombustible;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) 
    {
        String mensajeNew = "";
        defectoEncontrado = (fugasTubo.isSelected() || salidasAdicionales.isSelected() || AusenciaTaponesAceite.isSelected() || tapaCombustible.isSelected() || SalidasDiseno.isSelected()); // 
        Boolean douDefc = false;
        
        if (defectoEncontrado) 
        {
            mensaje = new StringBuilder("Prueba rechazada por: \n");
            Set<Integer> ev = mapStrRechazos.keySet();
//            System.out.println("------------------------------Se ha añadido el defecto 84018----------------------------");
//            conjuntoDefectos.add(84018);
            //1
            if (fugasTubo.isSelected()) 
            {
                int idDefectoTablaRechazoGases = 8;
//              mensaje.append(" 40103041 ".concat(chb84035.getText()));
                mensajeNew = mensajeNew +"-4.1.1.1.1 " +fugasTubo.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
                
               // mensaje.append("-4.1.1.1.1 ".concat(mensajeNew));
                conjuntoDefectos.add(84035);
                for (Integer i : ev) {
                    if (i == 84035) {
                        douDefc = true;
                    }
                }
                if (douDefc == false) {
                    str = fugasTubo.getText().replaceFirst("<html>", "");
//                    mapStrRechazos.put(84035," 40103041 ".concat(str.replaceAll("</html>", "; ")));
                     mapStrRechazos.put(84035,"4.1.1.1.1 ".concat(str.replaceAll("</html>", "; ")));
                }
            } else {
                conjuntoDefectos.remove(84035);
                mapStrRechazos.remove(84035);
            }
            douDefc = false;
            
            //2
            if (salidasAdicionales.isSelected()) 
            {
                
                mensajeNew = mensajeNew + "-4.1.1.1.2 "+ salidasAdicionales.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
//              mensaje.append(" 40103042 ".concat(chb84038.getText()));
               // mensaje.append("-4.1.1.1.2 ".concat(mensajeNew));
                conjuntoDefectos.add(84038);
                for (Integer i : ev) {
                    if (i == 84038) {
                        douDefc = true;
                    }
                }
                if (douDefc == false) {
                    str = salidasAdicionales.getText().replaceFirst("<html>", "");
//                  mapStrRechazos.put(84038," 40103042 ".concat(str.replaceAll("</html>", "; ")));
                    mapStrRechazos.put(84038," 4.1.1.1.2 ".concat(str.replaceAll("</html>", "; ")));
                }
            } else {
                conjuntoDefectos.remove(84038);
            }
            douDefc = false;
            
            //3
            if (AusenciaTaponesAceite.isSelected()) 
            {
                mensajeNew = mensajeNew + "-4.1.1.1.3 "+AusenciaTaponesAceite.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
                //mensaje.append("-4.1.1.1.3 ".concat(mensajeNew));
                conjuntoDefectos.add(84037);
                for (Integer i : ev) {
                    if (i == 84037) {
                        douDefc = true;
                    }
                }
                if (douDefc == false) {
                    str = AusenciaTaponesAceite.getText().replaceFirst("<html>", "");
                    mapStrRechazos.put(84037," 4.1.1.1.3 ".concat(str.replaceAll("</html>", "; ")));
                }
            } else {
                conjuntoDefectos.remove(84037);
                mapStrRechazos.remove(84037);
            }
            douDefc = false;
            
            //4
            if (tapaCombustible.isSelected()) 
            {
                
                mensajeNew = mensajeNew +"-4.1.1.1.4 " +tapaCombustible.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
               // mensaje.append("-4.1.1.1.4 ".concat(mensajeNew));
                conjuntoDefectos.add(84039);
                for (Integer i : ev) 
                {
                    if (i == 84039) 
                    {
                        douDefc = true;
                    }
                }
                if (douDefc == false) 
                {
                    str = tapaCombustible.getText().replaceFirst("<html>", "");
                    mapStrRechazos.put(84039, " 4.1.1.1.4 ".concat(str.replaceAll("</html>", "; ")));
                }
            }else{
                conjuntoDefectos.remove(84039);
                mapStrRechazos.remove(84039);
            }
          
//            //5
            if (SalidasDiseno.isSelected()) 
            {
                
                mensajeNew = mensajeNew + "-4.1.1.1.6 "+ SalidasDiseno.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
               // mensaje.append(" 4.1.1.1.6 ".concat(mensajeNew));
                conjuntoDefectos.add(84041);
                for (Integer i : ev) 
                {
                    if (i == 84041) 
                    {
                        douDefc = true;
                    }
                }
                if (douDefc == false) 
                {
                    str = SalidasDiseno.getText().replaceFirst("<html>", "");
                    mapStrRechazos.put(84041, " 4.1.1.1.6 ".concat(str.replaceAll("</html>", "; ")));
                }
            }else{
                conjuntoDefectos.remove(84041);
                mapStrRechazos.remove(84041);
            }
            
            mensaje.append(mensajeNew);
            ev = mapStrRechazos.keySet();
            for (Integer i : ev) {
                System.out.println(i);
            }
//            AddDefGases();
            System.out.println("------------");
        }
    }

    public static void main(String args[]) {
        try
        {
            String ActivarTapaLlenado = UtilPropiedades.cargarPropiedad("ActivarTapaLlenado", "propiedades.properties");
            boolean TapaLlenadoActivador = Boolean.parseBoolean(ActivarTapaLlenado);
            String ActivarSalidasAdicional = UtilPropiedades.cargarPropiedad("ActivarSalidasAdicional", "propiedades.properties");
            boolean alidasAdicionalActivador = Boolean.parseBoolean(ActivarSalidasAdicional);

            JFrame app = new JFrame();
            PanelVerificacionMoto panelC = new PanelVerificacionMoto(TapaLlenadoActivador, alidasAdicionalActivador);
            JOptionPane.showMessageDialog(null, panelC, "Inspeccion Sensorial", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            System.out.println("Error -----------------------------");
        }

    }

    public String getDetallesRechazos() {
        String detalleRechazos = new String();
        Set<Integer> lst = mapStrRechazos.keySet();
        for (Integer posDef : lst) {
            detalleRechazos = detalleRechazos.concat(mapStrRechazos.get(posDef));
        }
        System.out.println(detalleRechazos);
        return detalleRechazos;
    }
    //Agrega el defecto 80000 si alguno de los siguientes defectos es seleccionado - "Popayan"

}
