/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.soltelec.pruebasgases;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.soltelec.util.UtilPropiedades;

/**
 *
 * @author Gerencia Desarrollo de Soluciones Tecnologicas
 */
public class PanelVerificacionMoto extends javax.swing.JPanel implements java.awt.event.ActionListener {

    private final Set<Integer> conjuntoDefectos = new LinkedHashSet<>();
    private StringBuilder mensaje;
    private boolean defectoEncontrado;
    private StringBuilder detalleRechazo;
    private Map<Integer, String> mapStrRechazos = new HashMap<Integer, String>();
    String str;

    /**
     * Creates new form PanelVerificacionV2
     */
    public PanelVerificacionMoto(boolean ActivarTapaLlenado, boolean ActivarSalidasAdicional) 
    {
        initComponents();
        Dimension d = new java.awt.Dimension(583, 90);
        this.setSize(583, 127);
        setSize(d);
        chb84039.setVisible(ActivarTapaLlenado);
        chb84040.setVisible(ActivarSalidasAdicional);
    }

    public boolean isDefectoEncontrado() {
        return defectoEncontrado;
    }

    public StringBuilder getMensaje() {
        return mensaje;
    }

    public Set<Integer> getConjuntoDefectos() {
        return conjuntoDefectos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chb84035 = new javax.swing.JCheckBox();
        chb84035.addActionListener(this);
        chb84038 = new javax.swing.JCheckBox();
        chb84038.addActionListener(this);
        chb84037 = new javax.swing.JCheckBox();
        chb84037.addActionListener(this);
        jLabel1 = new javax.swing.JLabel();
        chb84039 = new javax.swing.JCheckBox();
        chb84039.addActionListener(this);
        chb84040 = new javax.swing.JCheckBox();
        chb84040.addActionListener(this);

        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 300));

        chb84035.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chb84035.setText("<html>Existencia de fugas en el tubo, uniones del múltiple y silenciador del sistema de escape del vehículo</html>");
        chb84035.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb84035ActionPerformed(evt);
            }
        });

        chb84038.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chb84038.setText("<html>Salidas adicionales en el sistema de escape diferentes a las de diseño original del vehículo</html>");

        chb84037.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chb84037.setText("<html>Ausencia de tapones de aceite o fugas en el mismo </html>");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VERIFICACION CONDICIONES ANORMALES");

        chb84039.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chb84039.setText("Presencia tapa llenado combustible");
        chb84039.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb84039ActionPerformed(evt);
            }
        });

        chb84040.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chb84040.setText("Salidas adicionales a las del diseño");
        chb84040.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb84040ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 118, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 131, Short.MAX_VALUE))
            .addComponent(chb84038)
            .addComponent(chb84037)
            .addComponent(chb84035, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chb84039, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(chb84040, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(chb84035, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chb84038, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chb84037, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chb84039)
                .addGap(18, 18, 18)
                .addComponent(chb84040)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chb84039ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb84039ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb84039ActionPerformed

    private void chb84040ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb84040ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb84040ActionPerformed

    private void chb84035ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb84035ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb84035ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chb84035;
    private javax.swing.JCheckBox chb84037;
    private javax.swing.JCheckBox chb84038;
    private javax.swing.JCheckBox chb84039;
    private javax.swing.JCheckBox chb84040;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) 
    {
        String mensajeNew = "";
        defectoEncontrado = (chb84035.isSelected() || chb84038.isSelected() || chb84037.isSelected() || chb84039.isSelected() || chb84040.isSelected()); // 
        Boolean douDefc = false;
        
        if (defectoEncontrado) 
        {
            mensaje = new StringBuilder("Prueba rechazada por: \n");
            Set<Integer> ev = mapStrRechazos.keySet();
//            System.out.println("------------------------------Se ha añadido el defecto 84018----------------------------");
//            conjuntoDefectos.add(84018);
            //1
            if (chb84035.isSelected()) 
            {
//              mensaje.append(" 40103041 ".concat(chb84035.getText()));
                mensajeNew = mensajeNew +"-4.1.1.1.1 " +chb84035.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
                
               // mensaje.append("-4.1.1.1.1 ".concat(mensajeNew));
                conjuntoDefectos.add(84035);
                for (Integer i : ev) {
                    if (i == 84035) {
                        douDefc = true;
                    }
                }
                if (douDefc == false) {
                    str = chb84035.getText().replaceFirst("<html>", "");
//                    mapStrRechazos.put(84035," 40103041 ".concat(str.replaceAll("</html>", "; ")));
                     mapStrRechazos.put(84035,"4.1.1.1.1 ".concat(str.replaceAll("</html>", "; ")));
                }
            } else {
                conjuntoDefectos.remove(84035);
                mapStrRechazos.remove(84035);
            }
            douDefc = false;
            
            //2
            if (chb84038.isSelected()) 
            {
                
                mensajeNew = mensajeNew + "-4.1.1.1.2 "+ chb84038.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
//              mensaje.append(" 40103042 ".concat(chb84038.getText()));
               // mensaje.append("-4.1.1.1.2 ".concat(mensajeNew));
                conjuntoDefectos.add(84038);
                for (Integer i : ev) {
                    if (i == 84038) {
                        douDefc = true;
                    }
                }
                if (douDefc == false) {
                    str = chb84038.getText().replaceFirst("<html>", "");
//                  mapStrRechazos.put(84038," 40103042 ".concat(str.replaceAll("</html>", "; ")));
                    mapStrRechazos.put(84038," 4.1.1.1.2 ".concat(str.replaceAll("</html>", "; ")));
                }
            } else {
                conjuntoDefectos.remove(84038);
            }
            douDefc = false;
            
            //3
            if (chb84037.isSelected()) 
            {
                mensajeNew = mensajeNew + "-4.1.1.1.3 "+chb84037.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
                //mensaje.append("-4.1.1.1.3 ".concat(mensajeNew));
                conjuntoDefectos.add(84037);
                for (Integer i : ev) {
                    if (i == 84037) {
                        douDefc = true;
                    }
                }
                if (douDefc == false) {
                    str = chb84037.getText().replaceFirst("<html>", "");
                    mapStrRechazos.put(84037," 4.1.1.1.3 ".concat(str.replaceAll("</html>", "; ")));
                }
            } else {
                conjuntoDefectos.remove(84037);
                mapStrRechazos.remove(84037);
            }
            douDefc = false;
            
            //4
            if (chb84039.isSelected()) 
            {
                
                mensajeNew = mensajeNew +"-4.1.1.1.4 " +chb84039.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
               // mensaje.append("-4.1.1.1.4 ".concat(mensajeNew));
                conjuntoDefectos.add(84039);
                for (Integer i : ev) 
                {
                    if (i == 84039) 
                    {
                        douDefc = true;
                    }
                }
                if (douDefc == false) 
                {
                    str = chb84039.getText().replaceFirst("<html>", "");
                    mapStrRechazos.put(84039, " 4.1.1.1.4 ".concat(str.replaceAll("</html>", "; ")));
                }
            }else{
                conjuntoDefectos.remove(84039);
                mapStrRechazos.remove(84039);
            }
          
//            //5
            if (chb84040.isSelected()) 
            {
                
                mensajeNew = mensajeNew + "-4.1.1.1.6 "+ chb84040.getText();
                mensajeNew = mensajeNew.replaceAll("<html>", " ");
                mensajeNew = mensajeNew.replaceAll("</html>", "; \n");
               // mensaje.append(" 4.1.1.1.6 ".concat(mensajeNew));
                conjuntoDefectos.add(84041);
                for (Integer i : ev) 
                {
                    if (i == 84041) 
                    {
                        douDefc = true;
                    }
                }
                if (douDefc == false) 
                {
                    str = chb84040.getText().replaceFirst("<html>", "");
                    mapStrRechazos.put(84041, " 4.1.1.1.6 ".concat(str.replaceAll("</html>", "; ")));
                }
            }else{
                conjuntoDefectos.remove(84041);
                mapStrRechazos.remove(84041);
            }
            
            mensaje.append(mensajeNew);
            ev = mapStrRechazos.keySet();
            for (Integer i : ev) {
                System.out.println(i);
            }
//            AddDefGases();
            System.out.println("------------");
        }
    }

    public static void main(String args[]) {
        try
        {
            String ActivarTapaLlenado = UtilPropiedades.cargarPropiedad("ActivarTapaLlenado", "propiedades.properties");
            boolean TapaLlenadoActivador = Boolean.parseBoolean(ActivarTapaLlenado);
            String ActivarSalidasAdicional = UtilPropiedades.cargarPropiedad("ActivarSalidasAdicional", "propiedades.properties");
            boolean alidasAdicionalActivador = Boolean.parseBoolean(ActivarSalidasAdicional);

            JFrame app = new JFrame();
            PanelVerificacionMoto panelC = new PanelVerificacionMoto(TapaLlenadoActivador, alidasAdicionalActivador);
            JOptionPane.showMessageDialog(null, panelC, "Inspeccion Sensorial", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            System.out.println("Error -----------------------------");
        }

    }

    public String getDetallesRechazos() {
        String detalleRechazos = new String();
        Set<Integer> lst = mapStrRechazos.keySet();
        for (Integer posDef : lst) {
            detalleRechazos = detalleRechazos.concat(mapStrRechazos.get(posDef));
        }
        System.out.println(detalleRechazos);
        return detalleRechazos;
    }
    //Agrega el defecto 80000 si alguno de los siguientes defectos es seleccionado - "Popayan"

}
