/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.soltelec.luxometro.lujan;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.soltelec.modulopuc.utilidades.Mensajes;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import java.awt.Component;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author GerenciaDesarrollo
 */
public class FrmComentario extends javax.swing.JDialog {
  java.awt.Frame frame;
  //---Conexión por JDBC
    private Connection conexion;
    private String usuario;
    private String password;
    private String direccionIP;
    private Long idPrueba;
    private String lblObservacion=" ";
    //DIRECCIÓN IP DEL SERVIDOR = 186.112.176.34
    //---
     

    FrmComentario() {
    }

    
    //////////////////////////////////////////////PARA NO PERDER LA REFERENCIA DEL OBJETO/////////

    public FrmComentario(Window owner,Long idPrueba,ModalityType modalityType) {
        super(owner,modalityType);       
        initComponents();
        Dimension d = new java.awt.Dimension(688, 172);
        setSize(d);
        setTitle("Inf. General");
        this.setLocationByPlatform(true);
        setResizable(false);   
        this.idPrueba=idPrueba;
        this.lblObservacion=" ";
    }
    
    public FrmComentario(Window owner,Long idPrueba,ModalityType modalityType,String lblObservacion) {
        super(owner,modalityType);       
        initComponents();
        Dimension d = new java.awt.Dimension(688, 172);
        setSize(d);
        setTitle("Inf. General");
        this.setLocationByPlatform(true);
        setResizable(false);   
        this.idPrueba=idPrueba;
        this.lblObservacion=lblObservacion;
    }
    

    private void cargarConexion() {
        
       
    }//end of method cargarUrlff

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtObservacion = new javax.swing.JScrollPane();
        txtComent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Observaciones Generales");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtObservacion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtComent.setColumns(20);
        txtComent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtComent.setLineWrap(true);
        txtComent.setRows(5);
        txtComent.setWrapStyleWord(true);
        txtObservacion.setViewportView(txtComent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = (Connection) DriverManager.getConnection(com.soltelec.modulopuc.configuracion.modelo.Conexion.getUrl(),com.soltelec.modulopuc.configuracion.modelo.Conexion.getUsuario() ,com.soltelec.modulopuc.configuracion.modelo.Conexion.getContraseña());
        } catch (ClassNotFoundException | SQLException ex) {
            Mensajes.mostrarExcepcion(ex);
        }

        try {
            conexion.setAutoCommit(false);
            String statement = "UPDATE pruebas SET observaciones=? WHERE Id_Pruebas = ? ";
            java.sql.PreparedStatement instruccion = conexion.prepareStatement(statement);
            if(this.lblObservacion.length()>3){
                instruccion.setString(1,this.lblObservacion.concat("; ").concat(this.txtComent.getText()));
            }else{
                instruccion.setString(1,this.txtComent.getText());
            }   
            instruccion.setLong(2, this.idPrueba);
            instruccion.executeUpdate();
            instruccion.clearParameters();
            conexion.commit();
            conexion.setAutoCommit(true);
            conexion.close();
            System.out.println("Datos enviados ".concat(this.txtComent.getText()));
        } catch (SQLException ex) {
            Mensajes.mostrarExcepcion(ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /////////////////////////////////MÉTODOS SOBRE LA FUNCIONALIDAD //////////////////////////////
   

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               
                
            }
        });
    }

   

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea txtComent;
    private javax.swing.JScrollPane txtObservacion;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = 0;
}
