/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Gerencia TIC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    private TipoVehiculo seleccionarTipoVehiculo(TipoVehiculo[] tipoVehiculos) {
        return (TipoVehiculo) JOptionPane.showInputDialog(null, "Seleccion el Tipo de Vehiculo", "Tipo de Vehiculo", JOptionPane.QUESTION_MESSAGE, null, tipoVehiculos, tipoVehiculos[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFreno = new javax.swing.JButton();
        btnSuspension = new javax.swing.JButton();
        btnDesviacion = new javax.swing.JButton();
        btnIntegracion = new javax.swing.JButton();
        btnServicio = new javax.swing.JButton();
        btnCalibracion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        btnPropiedades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFreno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rueda.png"))); // NOI18N
        btnFreno.setBorderPainted(false);
        btnFreno.setContentAreaFilled(false);
        btnFreno.setFocusable(false);
        btnFreno.setPreferredSize(new java.awt.Dimension(128, 128));
        btnFreno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ruedaCambio.png"))); // NOI18N
        btnFreno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFrenoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFrenoMouseExited(evt);
            }
        });
        btnFreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenoActionPerformed(evt);
            }
        });

        btnSuspension.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amortiguador.png"))); // NOI18N
        btnSuspension.setBorderPainted(false);
        btnSuspension.setContentAreaFilled(false);
        btnSuspension.setFocusable(false);
        btnSuspension.setPreferredSize(new java.awt.Dimension(128, 128));
        btnSuspension.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amortiguadorCambio.png"))); // NOI18N
        btnSuspension.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuspensionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuspensionMouseExited(evt);
            }
        });
        btnSuspension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspensionActionPerformed(evt);
            }
        });

        btnDesviacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desviacion.png"))); // NOI18N
        btnDesviacion.setBorderPainted(false);
        btnDesviacion.setContentAreaFilled(false);
        btnDesviacion.setFocusable(false);
        btnDesviacion.setPreferredSize(new java.awt.Dimension(128, 128));
        btnDesviacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desviacionCambio.png"))); // NOI18N
        btnDesviacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesviacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDesviacionMouseExited(evt);
            }
        });
        btnDesviacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesviacionActionPerformed(evt);
            }
        });

        btnIntegracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracionCambio.png"))); // NOI18N
        btnIntegracion.setBorderPainted(false);
        btnIntegracion.setContentAreaFilled(false);
        btnIntegracion.setFocusable(false);
        btnIntegracion.setPreferredSize(new java.awt.Dimension(128, 128));
        btnIntegracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        btnIntegracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIntegracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIntegracionMouseExited(evt);
            }
        });
        btnIntegracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegracionActionPerformed(evt);
            }
        });

        btnServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ensenanza.png"))); // NOI18N
        btnServicio.setBorderPainted(false);
        btnServicio.setContentAreaFilled(false);
        btnServicio.setFocusable(false);
        btnServicio.setPreferredSize(new java.awt.Dimension(128, 128));
        btnServicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ensenanzaCambio.png"))); // NOI18N
        btnServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServicioMouseExited(evt);
            }
        });
        btnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicioActionPerformed(evt);
            }
        });

        btnCalibracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/revicionInterior.png"))); // NOI18N
        btnCalibracion.setBorderPainted(false);
        btnCalibracion.setContentAreaFilled(false);
        btnCalibracion.setFocusable(false);
        btnCalibracion.setPreferredSize(new java.awt.Dimension(128, 128));
        btnCalibracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/revicionInteriorCambio.png"))); // NOI18N
        btnCalibracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalibracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalibracionMouseExited(evt);
            }
        });
        btnCalibracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalibracionActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fin.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusable(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(128, 128));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finCambio.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/solt.png"))); // NOI18N

        lblInformacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnPropiedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config.png"))); // NOI18N
        btnPropiedades.setBorderPainted(false);
        btnPropiedades.setContentAreaFilled(false);
        btnPropiedades.setFocusable(false);
        btnPropiedades.setPreferredSize(new java.awt.Dimension(48, 48));
        btnPropiedades.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configCambio.png"))); // NOI18N
        btnPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuspension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIntegracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalibracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 185, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSuspension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntegracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalibracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(lblInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrenoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrenoMouseEntered
        lblInformacion.setText("Freno");
    }//GEN-LAST:event_btnFrenoMouseEntered

    private void btnSuspensionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuspensionMouseEntered
        lblInformacion.setText("Suspensión");
    }//GEN-LAST:event_btnSuspensionMouseEntered

    private void btnDesviacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesviacionMouseEntered
        lblInformacion.setText("Desviación");
    }//GEN-LAST:event_btnDesviacionMouseEntered

    private void btnIntegracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIntegracionMouseEntered
        lblInformacion.setText("Integración");
    }//GEN-LAST:event_btnIntegracionMouseEntered

    private void btnServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicioMouseEntered
        lblInformacion.setText("Servicio");
    }//GEN-LAST:event_btnServicioMouseEntered

    private void btnCalibracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalibracionMouseEntered
        lblInformacion.setText("Calibración");
    }//GEN-LAST:event_btnCalibracionMouseEntered

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        lblInformacion.setText("Salir");
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnFrenoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrenoMouseExited
        lblInformacion.setText("");
    }//GEN-LAST:event_btnFrenoMouseExited

    private void btnSuspensionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuspensionMouseExited
        lblInformacion.setText("");
    }//GEN-LAST:event_btnSuspensionMouseExited

    private void btnDesviacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesviacionMouseExited
        lblInformacion.setText("");
    }//GEN-LAST:event_btnDesviacionMouseExited

    private void btnIntegracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIntegracionMouseExited
        lblInformacion.setText("");
    }//GEN-LAST:event_btnIntegracionMouseExited

    private void btnServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicioMouseExited
        lblInformacion.setText("");
    }//GEN-LAST:event_btnServicioMouseExited

    private void btnCalibracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalibracionMouseExited
        lblInformacion.setText("");
    }//GEN-LAST:event_btnCalibracionMouseExited

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        lblInformacion.setText("");
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnFrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenoActionPerformed
        TipoVehiculo[] tipoVehiculos = {TipoVehiculo.LIVIANO, TipoVehiculo.PESADO, TipoVehiculo.MOTO, TipoVehiculo.V4X4};
        TipoVehiculo tipoVehiculo = seleccionarTipoVehiculo(tipoVehiculos);
        
        if (tipoVehiculo == null) {
            return;
        }
        
        switch (tipoVehiculo) {
            case LIVIANO:
                new DlgIntegradoLiviano(this, 0, 0, 1, 0, 0,false,0,"","Liviano","","").setVisible(true);
                break;
            case PESADO:
                new DlgIntegradoPesado(this, 0, 1, 0, 0,2,false,0,"","Pesado","","").setVisible(true);
                break;
            case MOTO:
                new DlgFrenoMoto(this, true, 0, 0, 0,0,"MOTO","","").setVisible(true);
                break;
            case V4X4:
                new DlgIntegrado4x4(this, 0, 0, 1, 0, 0,0,"","Liviano","","").setVisible(true);
                break;
            default:                
                break;
        }
    }//GEN-LAST:event_btnFrenoActionPerformed

    private void btnSuspensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspensionActionPerformed
        TipoVehiculo[] tipoVehiculos = {TipoVehiculo.LIVIANO, TipoVehiculo.V4X4};
        TipoVehiculo tipoVehiculo = seleccionarTipoVehiculo(tipoVehiculos);
        
        if (tipoVehiculo == null) {
            return;
        }
        
        switch (tipoVehiculo) {
            case LIVIANO:
                new DlgIntegradoLiviano(this, 0, 1, 0, 0, 0,false,0,"","Liviano","","").setVisible(true);
                break;
            case V4X4:
                new DlgIntegrado4x4(this, 0, 1, 0, 0, 0,0,"","Liviano","","").setVisible(true);
                break;
            default:                
                break;
        }
    }//GEN-LAST:event_btnSuspensionActionPerformed

    private void btnDesviacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesviacionActionPerformed
        TipoVehiculo[] tipoVehiculos = {TipoVehiculo.LIVIANO, TipoVehiculo.PESADO, TipoVehiculo.V4X4};
        TipoVehiculo tipoVehiculo = seleccionarTipoVehiculo(tipoVehiculos);
        
        if (tipoVehiculo == null) {
            return;
        }
        
        switch (tipoVehiculo) {
            case LIVIANO:
                new DlgIntegradoLiviano(this, 1, 0, 0, 0, 0,false,0,"","Liviano","","").setVisible(true);
                break;
            case PESADO:
                new DlgIntegradoPesado(this, 1, 0, 0, 0,2,false,0,"","Pesado","","").setVisible(true);
                break;
            case V4X4:
                new DlgIntegrado4x4(this, 1, 0, 0, 0, 0,0,"","Liviano","","").setVisible(true);
                break;
            default:                
                break;
        }
    }//GEN-LAST:event_btnDesviacionActionPerformed

    private void btnIntegracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegracionActionPerformed
        TipoVehiculo[] tipoVehiculos = {TipoVehiculo.LIVIANO, TipoVehiculo.PESADO, TipoVehiculo.V4X4};
        TipoVehiculo tipoVehiculo = seleccionarTipoVehiculo(tipoVehiculos);
        
        if (tipoVehiculo == null) {
            return;
        }
        
        switch (tipoVehiculo) {
            case LIVIANO:
                new DlgIntegradoLiviano(this, 1, 1, 1, 0, 0,false,0,"","Liviano","","").setVisible(true);
                break;
            case PESADO:
                new DlgIntegradoPesado(this, 1, 1, 0, 0,2,false,0,"","Pesado","","").setVisible(true);
                break;
            case V4X4:
                new DlgIntegrado4x4(this, 1, 1, 1, 0, 0,0,"","Liviano","","").setVisible(true);
                break;
            default:                
                break;
        }
    }//GEN-LAST:event_btnIntegracionActionPerformed

    private void btnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicioActionPerformed
        new DlgServicio(this, true).setVisible(true);
    }//GEN-LAST:event_btnServicioActionPerformed

    private void btnCalibracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalibracionActionPerformed
        new DlgCalibracion(this, true).setVisible(true);
    }//GEN-LAST:event_btnCalibracionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedadesActionPerformed
        
    }//GEN-LAST:event_btnPropiedadesActionPerformed

    private enum TipoVehiculo {
        PESADO("Pesado"), LIVIANO("Liviano"), MOTO("Moto"), V4X4("4X4");
        private final String value;

        private TipoVehiculo(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return value;
        }
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                



}
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalibracion;
    private javax.swing.JButton btnDesviacion;
    private javax.swing.JButton btnFreno;
    private javax.swing.JButton btnIntegracion;
    private javax.swing.JButton btnPropiedades;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServicio;
    private javax.swing.JButton btnSuspension;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblInformacion;
    // End of variables declaration//GEN-END:variables
}
