marcaAnalizador=
modeloAnalizador=
serialElectronicoAnalizador=
modeloBanco=
marcaKit=
marcaTermo=
pefAnalizador=
serialAnalizador=
serialBanco=
serialKit=
serialBateria=
serialVibracion=
serialTemperatura=
serialTermo=
marcaOpacimetro=
modeloOpacimetro=
serialElectronicoOpac=
ltoeOpacimetro=
serialOpacimetro=