#obligatorios
marcaAnalizador=
marcaKit=
marcaTermo=
pefAnalizador=
serialAnalizador=
serialBanco=
serialKit=
serialBateria=
serialVibracion=
serialTemperatura=
serialTermo=
#obligatorios para diesel
marcaOpacimetro=
ltoeOpacimetro=
serialOpacimetro=
#opcionales
modeloAnalizador=
serialElectronicoAnalizador=
modeloBanco=
serialElectronicoOpac=
modeloOpacimetro=